name: alzimerapp
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  permission_handler: ^11.3.1
  image_picker: ^1.1.2
  flutter_colorpicker: ^1.1.0
  image: ^4.3.0
  share_plus: ^10.1.1
  provider: ^6.1.2
  google_fonts: ^6.2.1
  flutter_launcher_icons: ^0.14.1
  firebase_auth: ^5.3.3
  cloud_firestore: ^5.5.0
  firebase_core: ^3.8.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
     - lib/assets/bg.jpg
     - lib/assets/bg1.jpg
     - lib/assets/bg2.jpg
     - lib/assets/google.jpg
     - lib/assets/logo.png
     
flutter_icons:
  android: true
  ios: true
  image_path: "lib/assets/logo.png"  # Path to your logo image
  android_enable_rounded_icon: true
  remove_alpha_ios: true
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "lib/assets/logo.png"
